ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkq4vNY6YusxSoOuzgQyUAAnl7G1t6vCywZiug51kzkP7DiMxcyIG/6QegnzSw1yothX3NPKizdlLgfJNKlBGv7jq2xOKH0LY5UW8gv6QG22Nz2FrlpS0Kim8uk/PKr1eUFNw0W1eSYOh5qeiH6ykKJkfb2oUBJWy/m6q9v5AEzuEXmxruxgcIbrP8o+GKpdZ5sdRTf77C09k8J/BHUAhnyBjmEpFOL51R8QGZRxykpccWFGJR8P39z04CndzW4RMSy+I/1kfDqxHs9Iq5/bunvqD32Gks8SL8XAKvRTDC2m2ltYheFFuGHMpt0+pZ8rOuUx8zclxpWmge5xvl9SweQ== rsa-key-20210401
apiVersion: v1
data:
  values.yaml: |
    replicaCount: 2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: myconfig
  namespace: flux-system
